### ISSUE TITLE
README.md should have a quickstart guide

### ISSUE THREAD

**Issue by masmullin2000** [PhysixProject/physix#1]
A Quickstart guide would be nice
something like 

**Do this to run**
"cd <dirX>; ./runthething.sh; ./runtests.sh"

**Comment by PhysixProject** [comment]
Hi masmullin2000 

Thanks for filing this issue. 
This is what will be pushed to stable branch for next Beta-v2.9 release

Quickstart:
===========
1. Edit physix.conf: Identify the disk you will install to, by setting
   the CONF_ROOT_DEVICE variable.

2. Setup your disk partitions:
    ./catalyst -i physix.conf

3. cd /mnt/physix/opt/admin/physix ; ./BUILD_BASE_SYSTEM.sh

**Comment by PhysixProject** [comment]
Quickstart process has been merged on to the stable branch.
This should resolve this issue.
Thanks again, masmullin2000 :)
