### ISSUE TITLE
Drop support for LXDE desktop env.

### ISSUE THREAD

**Issue by treedavies** [PhysixProject/physix#30]
Remove Xorg, lightdm, and lxde.

very rarely used, no time to support it, nor care to.

Technically it will always be in the git change history, but 
will fall out of date over time.

**Comment by PhysixProject** [comment]
Done and pushed to mainline.
https://github.com/PhysixProject/physix/commit/e293cb01afc249df4abc4c9f83b6f92c6cf879ef
https://github.com/PhysixProject/physix/commit/e174eaa5a9fcd117e0b3bc0ec7793363e7d08387
