### ISSUE TITLE
Installing in a partition

### ISSUE THREAD

**Issue by EscarchaLite** [PhysixProject/physix#6]
Hi, this is just a question for installation. Can you install on a 62 gig partition? Or can you only use a blank device? Thanks for reading.

**Comment by PhysixProject** [comment]
At the moment, a completely blank device is required.  Installing to a partition is something I would like to have implemented at some point.

**Comment by PhysixProject** [comment]
Keeping this open as a reminder to do this.

**Comment by PhysixProject** [comment]
Tracking this for next Beta Release

**Comment by PhysixProject** [comment]
EscarchaLite,
Can you provide me with a description of how your disk is partitioned?
Do you use separate boot and uefi partitions?

**Comment by EscarchaLite** [comment]
> EscarchaLite,
> Can you provide me with a description of how your disk is partitioned?
> Do you use separate boot and uefi partitions?
Half is empty, the other half has openSUSE in it. I use UEFI

**Comment by PhysixProject** [comment]
This feature is now part of the stable branch.
Closing...
